## Question 01 - Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

# Answer :- 

Yes, there is a difference in the data type of variables list_ and array_list.

The variable list_ is a Python list object, while array_list is a NumPy ndarray object.

To print the data types of both variables, we can use the type() function as follows:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


## Question 02 - Write a code to print the data type of each and every element of both the variables list_ and arra_list.

# Answer :- 

Since the elements of the variable list_ are strings, we can use the type() function to print the data type of each element in the list. For the variable array_list, we can use the dtype attribute to print the data type of each element in the NumPy array.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# print data type of each element in list_
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

# print data type of each element in array_list
print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))


Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Question 03 - Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Answer :-

Yes, there will be a difference in the data type of the elements present in both the variables, list_ and array_list. When we define the dtype parameter as int while creating the NumPy array array_list, it converts all the elements of the original list to integers.

In [4]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
for element in list_:
    print(type(element))

# Print data types of elements in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## Question 04 - Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [8]:
# Answer :-

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Finding shape of num_array
print("Shape of num_array:", num_array.shape)

Shape of num_array: (2, 3)


In [9]:
# Finding size of num_array
print("Size of num_array:", num_array.size)

Size of num_array: 6


## Question 05 - Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
# Answer :- 

import numpy as np

# create a 3x3 numpy array containing zeros
arr = np.zeros((3, 3))

# print the array
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Question 06 - Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
# Answer :-

import numpy as np

identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
